name: Build beta

on:
  workflow_dispatch:
  push:
    branches: 
    - main

jobs:
  run-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Keystore
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $KEYSTORE_FILE | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/fenix.jks
      - name: Build
        env:
          KEYSTORE_FILE: ${{ runner.temp }}/keystore/fenix.jks
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew clean app:assembleBeta
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundles
          path: app/**/*.apk